#!/usr/bin/env python3
"""Generate the Unicode tables in src/ from the Unicode Character Database.

- src/linebreak_table.rs: for every code point, the resolved UAX #14 line
  breaking class plus the few extra properties the rules consult (East
  Asian Width, General_Category Pi/Pf, Extended_Pictographic on unassigned
  code points).
- src/normalize_table.rs: canonical combining classes, which characters
  are combining marks, canonical decompositions and primary composites.
- src/bidi_table.rs: bidirectional classes, paired brackets and mirrored
  glyphs (UAX #9), and joining types (for Arabic shaping).

It also writes the conformance test data used by tests/linebreak.rs,
tests/normalize.rs and tests/bidi.rs (comments stripped, compressed).

Usage: tools/gen_unicode.py [UCD_DIR]

UCD_DIR must contain LineBreak.txt, EastAsianWidth.txt,
DerivedGeneralCategory.txt, emoji-data.txt, UnicodeData.txt,
CompositionExclusions.txt, DerivedBidiClass.txt, BidiBrackets.txt,
BidiMirroring.txt, DerivedJoiningType.txt, LineBreakTest.txt, NormalizationTest.txt, BidiTest.txt
and BidiCharacterTest.txt of one Unicode version. Without it, the files for VERSION are downloaded from
the Unicode Consortium.
"""

import os
import re
import sys
import urllib.request
import zlib

VERSION = "17.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd/"
FILES = {
    "LineBreak.txt": "LineBreak.txt",
    "EastAsianWidth.txt": "EastAsianWidth.txt",
    "DerivedGeneralCategory.txt": "extracted/DerivedGeneralCategory.txt",
    "emoji-data.txt": "emoji/emoji-data.txt",
    "LineBreakTest.txt": "auxiliary/LineBreakTest.txt",
    "UnicodeData.txt": "UnicodeData.txt",
    "CompositionExclusions.txt": "CompositionExclusions.txt",
    "NormalizationTest.txt": "NormalizationTest.txt",
    "DerivedBidiClass.txt": "extracted/DerivedBidiClass.txt",
    "BidiBrackets.txt": "BidiBrackets.txt",
    "BidiMirroring.txt": "BidiMirroring.txt",
    "DerivedJoiningType.txt": "extracted/DerivedJoiningType.txt",
    "BidiTest.txt": "BidiTest.txt",
    "BidiCharacterTest.txt": "BidiCharacterTest.txt",
}

HEADER = """//! Derived from the Unicode Character Database, Copyright © 1991-2025
//! Unicode, Inc., under the Unicode License v3 (`LICENSE-UNICODE`)."""

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Classes after LB1 resolution (AI, SG, XX -> AL; SA -> CM or AL; CJ -> NS),
# in the order of the generated Rust enum.
CLASSES = """BK CR LF NL SP ZW ZWJ WJ GL CM BA BB B2 HY HH CB CL CP EX IN NS OP QU IS
NU PO PR SY AL HL ID EB EM H2 H3 JL JV JT RI AK AP AS VF VI""".split()

FLAG_EA, FLAG_PI, FLAG_PF, FLAG_EP_CN = 1, 2, 4, 8
MAX = 0x110000


def read(ucd, name):
    if ucd:
        with open(os.path.join(ucd, name), encoding="utf-8") as f:
            return f.read()
    with urllib.request.urlopen(BASE + FILES[name]) as r:
        return r.read().decode("utf-8")


def ranges(text, missing=True):
    """Yield (first, last, value) from a UCD file, @missing lines first."""
    for line in text.splitlines():
        m = re.match(r"#\s*@missing:\s*([0-9A-F]+)\.\.([0-9A-F]+)\s*;\s*(\w+)", line)
        if m and missing:
            yield int(m[1], 16), int(m[2], 16), m[3]
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        cps, value = (p.strip() for p in line.split(";")[:2])
        first, _, last = cps.partition("..")
        yield int(first, 16), int(last or first, 16), value


def prop(text, default):
    table = [default] * MAX
    for first, last, value in ranges(text):
        table[first : last + 1] = [value] * (last - first + 1)
    return table


def main():
    ucd = sys.argv[1] if len(sys.argv) > 1 else None
    lb = prop(read(ucd, "LineBreak.txt"), "XX")
    ea = prop(read(ucd, "EastAsianWidth.txt"), "N")
    gc = prop(read(ucd, "DerivedGeneralCategory.txt"), "Cn")
    ep = [False] * MAX
    for first, last, value in ranges(read(ucd, "emoji-data.txt"), missing=False):
        if value == "Extended_Pictographic":
            ep[first : last + 1] = [True] * (last - first + 1)

    packed = []
    for cp in range(MAX):
        c = lb[cp]
        if c in ("AI", "SG", "XX"):
            c = "AL"
        elif c == "SA":
            c = "CM" if gc[cp] in ("Mn", "Mc") else "AL"
        elif c == "CJ":
            c = "NS"
        flags = 0
        if ea[cp] in ("F", "W", "H"):
            flags |= FLAG_EA
        if c == "QU" and gc[cp] == "Pi":
            flags |= FLAG_PI
        if c == "QU" and gc[cp] == "Pf":
            flags |= FLAG_PF
        if ep[cp] and gc[cp] == "Cn":
            flags |= FLAG_EP_CN
        v = flags << 6 | CLASSES.index(c)
        if not packed or packed[-1][1] != v:
            packed.append((cp, v))

    out = []
    out.append(f"//! Unicode {VERSION} line breaking properties, generated by")
    out.append("//! `tools/gen_unicode.py`. Do not edit.")
    out.append("//!")
    out.append(HEADER)
    out.append("")
    out.append(f'pub const UNICODE_VERSION: &str = "{VERSION}";')
    out.append("")
    out.append("/// Line breaking classes after the LB1 resolution of AI, SG, XX, SA and CJ.")
    out.append("#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
    out.append("#[rustfmt::skip]")
    out.append("pub enum Class {")
    out.append("    " + ", ".join(CLASSES) + ",")
    out.append("}")
    out.append("")
    out.append("#[rustfmt::skip]")
    out.append(f"pub const CLASSES: [Class; {len(CLASSES)}] = [")
    for i in range(0, len(CLASSES), 12):
        out.append("    " + " ".join(f"Class::{c}," for c in CLASSES[i : i + 12]))
    out.append("];")
    out.append("")
    out.append(f"pub const FLAG_EA: u32 = {FLAG_EA};")
    out.append(f"pub const FLAG_PI: u32 = {FLAG_PI};")
    out.append(f"pub const FLAG_PF: u32 = {FLAG_PF};")
    out.append(f"pub const FLAG_EP_CN: u32 = {FLAG_EP_CN};")
    out.append("")
    out.append("/// Ranges of code points with equal properties, sorted by first code")
    out.append("/// point: `first << 11 | flags << 6 | class`. A range ends where the")
    out.append("/// next one starts.")
    out.append("#[rustfmt::skip]")
    out.append(f"pub static RANGES: [u32; {len(packed)}] = [")
    words = [f"0x{cp << 11 | v:08X}," for cp, v in packed]
    for i in range(0, len(words), 8):
        out.append("    " + " ".join(words[i : i + 8]))
    out.append("];")
    with open(os.path.join(ROOT, "src", "linebreak_table.rs"), "w") as f:
        f.write("\n".join(out) + "\n")

    os.makedirs(os.path.join(ROOT, "tests", "data"), exist_ok=True)
    write_test(read(ucd, "LineBreakTest.txt"), "LineBreakTest.txt.zlib", strip=False)
    print(f"{len(packed)} line breaking ranges, Unicode {VERSION}")
    normalization(ucd, gc)
    bidi(ucd)


def write_test(text, name, strip):
    """Compress a test file, keeping its first line (which names the version)."""
    lines = text.splitlines()
    if strip:
        body = [line.split("#", 1)[0].rstrip() for line in lines[1:]]
        lines = lines[:1] + [line for line in body if line]
    with open(os.path.join(ROOT, "tests", "data", name), "wb") as f:
        f.write(zlib.compress(("\n".join(lines) + "\n").encode("utf-8"), 9))


def normalization(ucd, gc):
    ccc = [0] * MAX
    decomp = {}
    for line in read(ucd, "UnicodeData.txt").splitlines():
        fields = line.split(";")
        cp = int(fields[0], 16)
        if fields[1].endswith(", Last>"):
            continue  # ranges (CJK, Hangul, ...) have no decompositions
        ccc[cp] = int(fields[3])
        d = fields[5]
        if d and not d.startswith("<"):
            decomp[cp] = [int(x, 16) for x in d.split()]
    excluded = set()
    for line in read(ucd, "CompositionExclusions.txt").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            first, _, last = line.partition("..")
            excluded.update(range(int(first, 16), int(last or first, 16) + 1))
    compose = []
    for cp, d in sorted(decomp.items()):
        # Full_Composition_Exclusion: listed exclusions, singletons and
        # non-starter decompositions.
        if len(d) == 2 and cp not in excluded and ccc[cp] == 0 and ccc[d[0]] == 0:
            compose.append((d[0], d[1], cp))
    compose.sort()

    packed = []
    for cp in range(MAX):
        mark = gc[cp] in ("Mn", "Mc", "Me")
        v = int(mark) << 8 | ccc[cp]
        if not packed or packed[-1][1] != v:
            packed.append((cp, v))

    out = [
        f"//! Unicode {VERSION} normalization data, generated by `tools/gen_unicode.py`.",
        "//! Do not edit.",
        "//!",
        HEADER,
        "",
        "/// Ranges of code points with equal properties, sorted by first code",
        "/// point: `first << 11 | is_mark << 8 | canonical_combining_class`, where",
        "/// `is_mark` means General_Category Mn, Mc or Me. A range ends where the",
        "/// next one starts.",
        "#[rustfmt::skip]",
        f"pub static CLASSES: [u32; {len(packed)}] = [",
    ]
    words = [f"0x{cp << 11 | v:08X}," for cp, v in packed]
    out += ["    " + " ".join(words[i : i + 8]) for i in range(0, len(words), 8)]
    out += [
        "];",
        "",
        "/// Canonical decompositions (one level): `(character, first, second)`,",
        "/// sorted; `second` is 0 for singletons. Hangul syllables are computed.",
        "#[rustfmt::skip]",
        f"pub static DECOMPOSITIONS: [(u32, u32, u32); {len(decomp)}] = [",
    ]
    items = [f"(0x{cp:X}, 0x{d[0]:X}, 0x{d[1] if len(d) > 1 else 0:X})," for cp, d in sorted(decomp.items())]
    out += ["    " + " ".join(items[i : i + 4]) for i in range(0, len(items), 4)]
    out += [
        "];",
        "",
        "/// Primary composites: `(first, second, composite)`, sorted. Hangul",
        "/// syllables are computed.",
        "#[rustfmt::skip]",
        f"pub static COMPOSITIONS: [(u32, u32, u32); {len(compose)}] = [",
    ]
    items = [f"(0x{a:X}, 0x{b:X}, 0x{c:X})," for a, b, c in compose]
    out += ["    " + " ".join(items[i : i + 4]) for i in range(0, len(items), 4)]
    out.append("];")
    with open(os.path.join(ROOT, "src", "normalize_table.rs"), "w") as f:
        f.write("\n".join(out) + "\n")
    write_test(read(ucd, "NormalizationTest.txt"), "NormalizationTest.txt.zlib", strip=True)
    print(f"{len(packed)} class ranges, {len(decomp)} decompositions, {len(compose)} compositions")


# Bidirectional classes, in the order of the generated Rust enum.
BIDI_CLASSES = """L R AL EN ES ET AN CS NSM BN B S WS ON LRE LRO RLE RLO PDF LRI RLI FSI
PDI""".split()


# Long names of the bidirectional classes, used by @missing lines.
BIDI_LONG = {
    "Left_To_Right": "L", "Right_To_Left": "R", "Arabic_Letter": "AL", "European_Number": "EN",
    "European_Separator": "ES", "European_Terminator": "ET", "Arabic_Number": "AN",
    "Common_Separator": "CS", "Nonspacing_Mark": "NSM", "Boundary_Neutral": "BN",
    "Paragraph_Separator": "B", "Segment_Separator": "S", "White_Space": "WS", "Other_Neutral": "ON",
}


# Joining types: non-joining, right, left, dual, join causing, transparent.
JOINING_TYPES = "U R L D C T".split()


def bidi(ucd):
    bc = [BIDI_LONG.get(c, c) for c in prop(read(ucd, "DerivedBidiClass.txt"), "L")]
    packed = []
    for cp in range(MAX):
        v = BIDI_CLASSES.index(bc[cp])
        if not packed or packed[-1][1] != v:
            packed.append((cp, v))
    brackets = []
    for line in read(ucd, "BidiBrackets.txt").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            cp, pair, kind = (p.strip() for p in line.split(";"))
            brackets.append((int(cp, 16), int(pair, 16), kind == "o"))
    mirrors = []
    for first, _, value in ranges(read(ucd, "BidiMirroring.txt"), missing=False):
        mirrors.append((first, int(value, 16)))
    jt = prop(read(ucd, "DerivedJoiningType.txt"), "U")
    joining = []
    for cp in range(MAX):
        v = JOINING_TYPES.index({"Non_Joining": "U"}.get(jt[cp], jt[cp]))
        if not joining or joining[-1][1] != v:
            joining.append((cp, v))

    out = [
        f"//! Unicode {VERSION} bidirectional and joining data, generated by `tools/gen_unicode.py`.",
        "//! Do not edit.",
        "//!",
        HEADER,
        "",
        "/// Bidirectional character types (Bidi_Class).",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "#[rustfmt::skip]",
        "pub enum BidiClass {",
        "    " + ", ".join(BIDI_CLASSES) + ",",
        "}",
        "",
        "#[rustfmt::skip]",
        f"pub const BIDI_CLASSES: [BidiClass; {len(BIDI_CLASSES)}] = [",
    ]
    out += ["    " + " ".join(f"BidiClass::{c}," for c in BIDI_CLASSES[i : i + 8]) for i in range(0, len(BIDI_CLASSES), 8)]
    out += [
        "];",
        "",
        "/// Ranges of code points with the same class, sorted by first code point:",
        "/// `first << 5 | class`. A range ends where the next one starts.",
        "#[rustfmt::skip]",
        f"pub static RANGES: [u32; {len(packed)}] = [",
    ]
    words = [f"0x{cp << 5 | v:08X}," for cp, v in packed]
    out += ["    " + " ".join(words[i : i + 8]) for i in range(0, len(words), 8)]
    out += [
        "];",
        "",
        "/// Paired brackets: `(bracket, its pair, is_opening)`, sorted.",
        "#[rustfmt::skip]",
        f"pub static BRACKETS: [(u32, u32, bool); {len(brackets)}] = [",
    ]
    items = [f"(0x{a:X}, 0x{b:X}, {'true' if o else 'false'})," for a, b, o in brackets]
    out += ["    " + " ".join(items[i : i + 4]) for i in range(0, len(items), 4)]
    out += [
        "];",
        "",
        "/// Bidi_Mirroring_Glyph: `(character, mirrored character)`, sorted.",
        "#[rustfmt::skip]",
        f"pub static MIRRORS: [(u32, u32); {len(mirrors)}] = [",
    ]
    items = [f"(0x{a:X}, 0x{b:X})," for a, b in mirrors]
    out += ["    " + " ".join(items[i : i + 6]) for i in range(0, len(items), 6)]
    out += [
        "];",
        "",
        "/// Joining types (Joining_Type), for cursive scripts such as Arabic.",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "#[rustfmt::skip]",
        "pub enum JoiningType {",
        "    " + ", ".join(JOINING_TYPES) + ",",
        "}",
        "",
        "#[rustfmt::skip]",
        f"pub const JOINING_TYPES: [JoiningType; {len(JOINING_TYPES)}] = [",
        "    " + " ".join(f"JoiningType::{t}," for t in JOINING_TYPES),
        "];",
        "",
        "/// Ranges of code points with the same joining type, sorted by first",
        "/// code point: `first << 3 | type`. A range ends where the next one",
        "/// starts.",
        "#[rustfmt::skip]",
        f"pub static JOINING: [u32; {len(joining)}] = [",
    ]
    words = [f"0x{cp << 3 | v:08X}," for cp, v in joining]
    out += ["    " + " ".join(words[i : i + 8]) for i in range(0, len(words), 8)]
    out.append("];")
    with open(os.path.join(ROOT, "src", "bidi_table.rs"), "w") as f:
        f.write("\n".join(out) + "\n")
    write_test(read(ucd, "BidiTest.txt"), "BidiTest.txt.zlib", strip=True)
    write_test(read(ucd, "BidiCharacterTest.txt"), "BidiCharacterTest.txt.zlib", strip=True)
    print(
        f"{len(packed)} bidi class ranges, {len(brackets)} brackets, {len(mirrors)} mirrors, "
        f"{len(joining)} joining ranges"
    )


if __name__ == "__main__":
    main()
