#!/usr/bin/env python3
"""Generate src/linebreak_table.rs from the Unicode Character Database.

The table holds, for every code point, the resolved UAX #14 line breaking
class plus the few extra properties the rules consult (East Asian Width,
General_Category Pi/Pf, Extended_Pictographic on unassigned code points).
It also writes the conformance test data used by tests/linebreak.rs.

Usage: tools/gen_linebreak.py [UCD_DIR]

UCD_DIR must contain LineBreak.txt, EastAsianWidth.txt,
DerivedGeneralCategory.txt, emoji-data.txt and LineBreakTest.txt of one
Unicode version. Without it, the files for VERSION are downloaded from the
Unicode Consortium.
"""

import os
import re
import sys
import urllib.request
import zlib

VERSION = "17.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd/"
FILES = {
    "LineBreak.txt": "LineBreak.txt",
    "EastAsianWidth.txt": "EastAsianWidth.txt",
    "DerivedGeneralCategory.txt": "extracted/DerivedGeneralCategory.txt",
    "emoji-data.txt": "emoji/emoji-data.txt",
    "LineBreakTest.txt": "auxiliary/LineBreakTest.txt",
}

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Classes after LB1 resolution (AI, SG, XX -> AL; SA -> CM or AL; CJ -> NS),
# in the order of the generated Rust enum.
CLASSES = """BK CR LF NL SP ZW ZWJ WJ GL CM BA BB B2 HY HH CB CL CP EX IN NS OP QU IS
NU PO PR SY AL HL ID EB EM H2 H3 JL JV JT RI AK AP AS VF VI""".split()

FLAG_EA, FLAG_PI, FLAG_PF, FLAG_EP_CN = 1, 2, 4, 8
MAX = 0x110000


def read(ucd, name):
    if ucd:
        with open(os.path.join(ucd, name), encoding="utf-8") as f:
            return f.read()
    with urllib.request.urlopen(BASE + FILES[name]) as r:
        return r.read().decode("utf-8")


def ranges(text, missing=True):
    """Yield (first, last, value) from a UCD file, @missing lines first."""
    for line in text.splitlines():
        m = re.match(r"#\s*@missing:\s*([0-9A-F]+)\.\.([0-9A-F]+)\s*;\s*(\w+)", line)
        if m and missing:
            yield int(m[1], 16), int(m[2], 16), m[3]
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        cps, value = (p.strip() for p in line.split(";")[:2])
        first, _, last = cps.partition("..")
        yield int(first, 16), int(last or first, 16), value


def prop(text, default):
    table = [default] * MAX
    for first, last, value in ranges(text):
        table[first : last + 1] = [value] * (last - first + 1)
    return table


def main():
    ucd = sys.argv[1] if len(sys.argv) > 1 else None
    lb = prop(read(ucd, "LineBreak.txt"), "XX")
    ea = prop(read(ucd, "EastAsianWidth.txt"), "N")
    gc = prop(read(ucd, "DerivedGeneralCategory.txt"), "Cn")
    ep = [False] * MAX
    for first, last, value in ranges(read(ucd, "emoji-data.txt"), missing=False):
        if value == "Extended_Pictographic":
            ep[first : last + 1] = [True] * (last - first + 1)

    packed = []
    for cp in range(MAX):
        c = lb[cp]
        if c in ("AI", "SG", "XX"):
            c = "AL"
        elif c == "SA":
            c = "CM" if gc[cp] in ("Mn", "Mc") else "AL"
        elif c == "CJ":
            c = "NS"
        flags = 0
        if ea[cp] in ("F", "W", "H"):
            flags |= FLAG_EA
        if c == "QU" and gc[cp] == "Pi":
            flags |= FLAG_PI
        if c == "QU" and gc[cp] == "Pf":
            flags |= FLAG_PF
        if ep[cp] and gc[cp] == "Cn":
            flags |= FLAG_EP_CN
        v = flags << 6 | CLASSES.index(c)
        if not packed or packed[-1][1] != v:
            packed.append((cp, v))

    out = []
    out.append(f"//! Unicode {VERSION} line breaking properties, generated by")
    out.append("//! `tools/gen_linebreak.py`. Do not edit.")
    out.append("//!")
    out.append("//! Derived from the Unicode Character Database, Copyright © 1991-2025")
    out.append("//! Unicode, Inc., under the Unicode License v3 (`LICENSE-UNICODE`).")
    out.append("")
    out.append(f'pub const UNICODE_VERSION: &str = "{VERSION}";')
    out.append("")
    out.append("/// Line breaking classes after the LB1 resolution of AI, SG, XX, SA and CJ.")
    out.append("#[derive(Clone, Copy, Debug, PartialEq, Eq)]")
    out.append("#[rustfmt::skip]")
    out.append("pub enum Class {")
    out.append("    " + ", ".join(CLASSES) + ",")
    out.append("}")
    out.append("")
    out.append("#[rustfmt::skip]")
    out.append(f"pub const CLASSES: [Class; {len(CLASSES)}] = [")
    for i in range(0, len(CLASSES), 12):
        out.append("    " + " ".join(f"Class::{c}," for c in CLASSES[i : i + 12]))
    out.append("];")
    out.append("")
    out.append(f"pub const FLAG_EA: u32 = {FLAG_EA};")
    out.append(f"pub const FLAG_PI: u32 = {FLAG_PI};")
    out.append(f"pub const FLAG_PF: u32 = {FLAG_PF};")
    out.append(f"pub const FLAG_EP_CN: u32 = {FLAG_EP_CN};")
    out.append("")
    out.append("/// Ranges of code points with equal properties, sorted by first code")
    out.append("/// point: `first << 11 | flags << 6 | class`. A range ends where the")
    out.append("/// next one starts.")
    out.append("#[rustfmt::skip]")
    out.append(f"pub static RANGES: [u32; {len(packed)}] = [")
    words = [f"0x{cp << 11 | v:08X}," for cp, v in packed]
    for i in range(0, len(words), 8):
        out.append("    " + " ".join(words[i : i + 8]))
    out.append("];")
    with open(os.path.join(ROOT, "src", "linebreak_table.rs"), "w") as f:
        f.write("\n".join(out) + "\n")

    test = read(ucd, "LineBreakTest.txt").encode("utf-8")
    os.makedirs(os.path.join(ROOT, "tests", "data"), exist_ok=True)
    with open(os.path.join(ROOT, "tests", "data", "LineBreakTest.txt.zlib"), "wb") as f:
        f.write(zlib.compress(test, 9))
    print(f"{len(packed)} ranges, Unicode {VERSION}")


if __name__ == "__main__":
    main()
